n_workers: 16
output_path: /home/mason/full_runs/python/fast_implementation_comparison
write_state: False
write_images: False
write_all_craters: False

run_configurations:
  - 1.00_3.00_0.40_1.50:
      slope: 1.00
      r_stat_multiplier: 3.00
      min_rim_percentage: 0.40
      effective_radius_multiplier: 1.50
      study_region_size: 10000
      study_region_padding: 1250
      min_crater_radius: 2.5
      max_crater_radius: 2500
      stop_condition:
        name: crater_count_and_areal_density
      n_simulations: 3

  - 1.50_7.00_0.50_1.10:
      slope: 1.50
      r_stat_multiplier: 7.00
      min_rim_percentage: 0.50
      effective_radius_multiplier: 1.10
      study_region_size: 10000
      study_region_padding: 1250
      min_crater_radius: 2.5
      max_crater_radius: 2500
      stop_condition:
        name: crater_count_and_areal_density
      n_simulations: 3

  - 2.00_5.00_0.60_1.90:
        slope: 2.00
        r_stat_multiplier: 5.00
        min_rim_percentage: 0.60
        effective_radius_multiplier: 1.90
        study_region_size: 10000
        study_region_padding: 1250
        min_crater_radius: 2.5
        max_crater_radius: 2500
        stop_condition:
          name: crater_count_and_areal_density
        n_simulations: 3

  - 2.50_7.00_0.60_1.30:
        slope: 2.50
        r_stat_multiplier: 7.00
        min_rim_percentage: 0.60
        effective_radius_multiplier: 1.30
        study_region_size: 10000
        study_region_padding: 1250
        min_crater_radius: 2.5
        max_crater_radius: 2500
        stop_condition:
          name: crater_count_and_areal_density
        n_simulations: 3

  - 3.00_9.00_0.60_1.90:
        slope: 3.00
        r_stat_multiplier: 9.00
        min_rim_percentage: 0.60
        effective_radius_multiplier: 1.90
        study_region_size: 10000
        study_region_padding: 1250
        min_crater_radius: 2.5
        max_crater_radius: 2500
        stop_condition:
          name: crater_count_and_areal_density
        n_simulations: 3