random_seed: 123
n_simulations_per_corner_point_and_center: 10
n_simulations_for_interior: 25000
n_simulations_per_interior_config: 500

n_workers: 25
config_output_path: /data/saturation/config
run_output_path: /data/saturation/surface_runs_improved2
write_state: False
write_images: False
write_all_craters: False
write_removals: False

base_config:
  study_region_size: 10000
  study_region_padding: 1250
  min_crater_radius: 2.5
  max_crater_radius: 2500
  stop_condition:
    name: crater_count_and_areal_density
  n_simulations: 1

parameters:
  - slope:
      min: 1.25
      max: 2.0
      stdev: 0.05
  - r_stat_multiplier:
      min: 5.0
      max: 7.0
      stdev: 0.1
  - min_rim_percentage:
      min: 0.4
      max: 0.6
      stdev: 0.05
  - effective_radius_multiplier:
      min: 1.3
      max: 1.5
      stdev: 0.05
