random_seed: 123
n_simulations_per_corner_point_and_center: 10
n_simulations_for_interior: 25000
n_simulations_per_interior_config: 500

n_workers: 28
config_output_path: /data/saturation/r_stat_changes/config
run_output_path: /data/saturation/r_stat_changes

write_statistics_cadence: 100000
write_state_cadence: 0
write_image_cadence: 0

base_config:
  study_region_size: 10000
  study_region_padding: 1250
  min_crater_radius: 10
  max_crater_radius: 2500
  stop_condition:
    name: crater_count_and_areal_density
  n_simulations: 1

parameters:
  - slope:
      min: 1.0
      max: 2.0
      stdev: 0.01
  - r_stat_multiplier:
      min: 3.0
      max: 9.0
      stdev: 0.05
  - min_rim_percentage:
      min: 0.3
      max: 0.7
      stdev: 0.005
  - effective_radius_multiplier:
      min: 1.3
      max: 1.9
      stdev: 0.01
