random_seed: 123
n_simulations_per_corner_point_and_center: 1
n_simulations_for_interior: 25000
n_simulations_per_interior_config: 1000

n_workers: 24
config_output_path: /data/saturation/random_runs_large/config
run_output_path: /data/saturation/random_runs_large

write_statistics_cadence: 100000
write_state_cadence: 0
write_image_cadence: 0

base_config:
  study_region_size: 10000
  study_region_padding: 1250
  min_crater_radius: 2.5
  max_crater_radius: 2500
  stop_condition:
    name: crater_count_and_areal_density
  n_simulations: 1

parameters:
  - slope:
      min: 1.0
      max: 3.0
      stdev: 0.05
  - r_stat_multiplier:
      min: 3.0
      max: 9.0
      stdev: 0.1
  - min_rim_percentage:
      min: 0.4
      max: 0.6
      stdev: 0.05
  - effective_radius_multiplier:
      min: 1.1
      max: 1.9
      stdev: 0.05
