random_seed: 123
n_simulations_per_location: 3
n_levels: 4

n_workers: 24
config_output_path: /data/saturation/central_composite_design/ccd9_holdout/config
run_output_path: /data/saturation/central_composite_design/ccd9_holdout

write_statistics_cadence: 100000
write_craters_cadence: 100000
write_crater_removals_cadence: 100000
write_state_cadence: 0
write_image_cadence: 10000
write_image_points: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000, 20000, 21000, 22000, 23000, 24000, 25000]

base_config:
  study_region_size: 10000
  study_region_padding: 1250
  min_crater_radius: 10
  max_crater_radius: 2500
  stop_condition:
    name: areal_density
    percentage_increase: .01
    min_craters: 500000
  spatial_hash_cell_size: 25

parameters:
  - slope:
      min: 1.2
      max: 2.8
  - r_stat_multiplier:
      min: 3.5
      max: 8.5
  - min_rim_percentage:
      min: 0.35
      max: 0.65
  - effective_radius_multiplier:
      min: 1.25
      max: 1.75
