n_workers: 5
output_path: /home/mason/full_runs/python/sfd_comparison
write_state: True
write_images: False
write_all_craters: False

run_configurations:
  - 1.00_3.00_0.40_1.50:
      slope: 1.00
      erat: 3.00
      mrp: 0.40
      rmult: 1.50
      study_region_size: 10000
      study_region_padding: 1250
      min_crater_radius: 2.5
      max_crater_radius: 2500
      stop_condition:
        name: crater_count_and_areal_density
      n_simulations: 5

  - 1.50_7.00_0.50_1.10:
      slope: 1.50
      erat: 7.00
      mrp: 0.50
      rmult: 1.10
      study_region_size: 10000
      study_region_padding: 1250
      min_crater_radius: 2.5
      max_crater_radius: 2500
      stop_condition:
        name: crater_count_and_areal_density
      n_simulations: 5

  - 2.00_5.00_0.60_1.90:
        slope: 2.00
        erat: 5.00
        mrp: 0.60
        rmult: 1.90
        study_region_size: 10000
        study_region_padding: 1250
        min_crater_radius: 2.5
        max_crater_radius: 2500
        stop_condition:
          name: crater_count_and_areal_density
        n_simulations: 5
#
#  - 2.50_7.00_0.60_1.30:
#        slope: 2.50
#        erat: 7.00
#        mrp: 0.60
#        rmult: 1.30
#        study_region_size: 10000
#        study_region_padding: 1250
#        min_crater_radius: 2.5
#        max_crater_radius: 2500
#        stop_condition:
#          name: crater_count_and_areal_density
#        n_simulations: 30
#
#  - 3.00_9.00_0.60_1.90:
#        slope: 3.00
#        erat: 9.00
#        mrp: 0.60
#        rmult: 1.90
#        study_region_size: 10000
#        study_region_padding: 1250
#        min_crater_radius: 2.5
#        max_crater_radius: 2500
#        stop_condition:
#          name: crater_count_and_areal_density
#        n_simulations: 30