n_workers: 3
output_path: /home/mason/full_runs/python/functionality_testing

run_configurations:
  - 1.00_3.00_0.40_1.50:
      slope: 1.00
      r_stat_multiplier: 3.00
      min_rim_percentage: 0.40
      effective_radius_multiplier: 1.50
      study_region_size: 10000
      study_region_padding: 1250
      min_crater_radius: 2.5
      max_crater_radius: 2500
      n_craters: 500
      n_simulations: 3