n_workers: 10
output_path: /data/saturation/timing_tests/python310
write_crater_removals_cadence: 100000
write_craters_cadence: 100000
write_image_cadence: 10000
write_image_points:
- 100
- 200
- 300
- 400
- 500
- 600
- 700
- 800
- 900
- 1000
- 1500
- 2000
- 2500
- 3000
- 3500
- 4000
- 4500
- 5000
- 6000
- 7000
- 8000
- 9000
- 10000
- 11000
- 12000
- 13000
- 14000
- 15000
- 16000
- 17000
- 18000
- 19000
- 20000
- 21000
- 22000
- 23000
- 24000
- 25000
write_state_cadence: 0
write_statistics_cadence: 100000


run_configurations:
- 1:
    effective_radius_multiplier: 1.1
    max_crater_radius: 2500
    min_crater_radius: 10
    min_rim_percentage: 0.25
    r_stat_multiplier: 3.0
    random_seed: 2991312382
    simulation_name: python310_1
    slope: 1.0
    spatial_hash_cell_size: 25
    stop_condition:
      min_craters: 250000
      name: areal_density
      percentage_increase: 0.05
    study_region_padding: 1250
    study_region_size: 10000

- 2:
    effective_radius_multiplier: 1.5
    max_crater_radius: 2500
    min_crater_radius: 10
    min_rim_percentage: 0.5
    r_stat_multiplier: 5.0
    random_seed: 29913123833
    simulation_name: python310_2
    slope: 1.5
    spatial_hash_cell_size: 25
    stop_condition:
      min_craters: 250000
      name: areal_density
      percentage_increase: 0.05
    study_region_padding: 1250
    study_region_size: 10000

- 3:
    effective_radius_multiplier: 1.7
    max_crater_radius: 2500
    min_crater_radius: 10
    min_rim_percentage: 0.5
    r_stat_multiplier: 5.0
    random_seed: 29913123813
    simulation_name: python310_3
    slope: 2.5
    spatial_hash_cell_size: 25
    stop_condition:
      min_craters: 250000
      name: areal_density
      percentage_increase: 0.05
    study_region_padding: 1250
    study_region_size: 10000
