n_workers: 1
output_path: /tmp/test_rim_updates
write_image_cadence: 0
write_state_cadence: 0
write_statistics_cadence: 100000

run_configurations:
  - corner_point_1.896_0.701_8.961_2.011:
      rmult: 1.8962772826864172
      max_crater_radius: 2500
      min_crater_radius: 10
      mrp: 0.7013261697919915
      n_simulations: 1
      erat: 8.960591722055616
      slope: 2.0114065624294746
      stop_condition:
        name: crater_count_and_areal_density
      study_region_padding: 1250
      study_region_size: 10000
