n_workers: 1
output_path: /data/saturation/tests/test_timings_python_3.11_10x
write_statistics_cadence: 1000
write_state_cadence: 0
write_image_cadence: 0

run_configurations:
  - test_timings:
        effective_radius_multiplier: 1.5
        min_rim_percentage: 0.4
        r_stat_multiplier: 5.0
        slope: 2.5
        study_region_size: 1000000
        study_region_padding: 12500
        min_crater_radius: 25
        max_crater_radius: 25000
        stop_condition:
          name: n_craters
          n_craters: 500000000
        n_simulations: 1