random_seed: 321
n_workers: 5
n_simulations: 5
n_simulations_per_config: 1000

write_statistics_cadence: 50000
write_craters_cadence: 50000
write_crater_removals_cadence: 50000
write_state_cadence: 0
write_image_cadence: 0
write_image_points: []

base_config:
  study_region_size: 12000
  study_region_padding: 1500
  min_crater_radius: 3
  max_crater_radius: 3000
  stop_condition:
    name: n_craters
    n_craters: 50000000
  spatial_hash_cell_size: 10

parameters:
  - slope:
      min: 1.1
      max: 1.2
  - r_stat_multiplier:
      min: 7.0
      max: 7.1
  - min_rim_percentage:
      min: 0.5
      max: 0.75
  - effective_radius_multiplier:
      min: 1.8
      max: 1.9
