random_seed: 234
n_workers: 28
n_simulations: 1000
n_simulations_per_config: 1000

write_statistics_cadence: 100000
write_craters_cadence: 100000
write_crater_removals_cadence: 100000
write_state_cadence: 0
write_image_cadence: 0
write_image_points: []

base_config:
  study_region_size: 2000
  study_region_padding: 250
  min_crater_radius: 5
  max_crater_radius: 500
  stop_condition:
    name: n_craters_max
    percentage_increase: 0.0
    min_craters: 500000
  spatial_hash_cell_size: 10

parameters:
  - slope:
      min: 1.0
      max: 3.0
  - r_stat_multiplier:
      min: 6.0
      max: 15.0
  - min_rim_percentage:
      min: 0.25
      max: 0.75
  - effective_radius_multiplier:
      min: 1.1
      max: 1.9
